name: Build Typescript

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build typescript
    - run: npm install
    - run: npm run build
        
